site_name:        LITS.jl
repo_url:         https://github.com/Energy-MAC/LITS.jl
site_description: Description
site_author:      Energy-MAC

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - LITS: api/LITS.md
  - Models: Models/gens.md
